version: '3'
services:
    mysql:
        image: {{{ IMAGE }}}
        container_name: {{{ CONTAINER_NAME }}}
        network_mode: bridge
        restart: always
        environment:
            - SERVICE_3306_NAME={{{ SERVICE_NAME }}}
            - SERVICE_3306_CHECK_TCP=true
            - SERVICE_3306_CHECK_INTERVAL=30s
            - SERVICE_3306_CHECK_TIMEOUT=10s
            - MYSQL_ROOT_PASSWORD={{{ PASSWD }}}
              #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "3306"
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
